=== lesfoster/cylindrical-alignment-app/data_source/src/conf/xml-resources/jaxb/cyl/cylinder.xsd
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:annotation>
    <xsd:documentation xml:lang="en">
      Cylindrical Blast Viewer: allows viewing of Biomolecular
      alignment data, in 3D, by forming the alignments into a
      cylinder, such that the alignments area arranged like the staves
      of a barrel. The cylinder can spin, and if it spins, it can
      do so at two different speeds.  When stopped, properties can
      be seen for the aligned values.
      Copyright (C) 2005 Leslie L. Foster

      This program is free software; you can redistribute it and/or
      modify it under the terms of the GNU General Public License
      as published by the Free Software Foundation; either version 2
      of the License, or (at your option) any later version.

      This program is distributed in the hope that it will be useful,
      but WITHOUT ANY WARRANTY; without even the implied warranty of
      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
      GNU General Public License for more details.

      You should have received a copy of the GNU General Public License
      along with this program; if not, write to the Free Software
      Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
    </xsd:documentation>
  </xsd:annotation>

  <xsd:element name="cylinder">
    <xsd:complexType>

      <xsd:sequence>

        <xsd:element name="entity" minOccurs="1" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:sequence>

              <xsd:element name="subentity" minOccurs="1" maxOccurs="unbounded">
                <xsd:complexType>
                  <xsd:sequence>

                    <xsd:element name="p" minOccurs="0" maxOccurs="unbounded">
                      <xsd:complexType>
                        <xsd:attribute name="name" type="xsd:string" />
                        <xsd:attribute name="value" type="xsd:string" />
                      </xsd:complexType>
                    </xsd:element>

                  </xsd:sequence>
                  <xsd:attribute name="strand" type="StrandType" use="required" />
                  <xsd:attribute name="send" type="positiveInt" use="required" />
                  <xsd:attribute name="sstart" type="positiveInt" use="required" />
                  <xsd:attribute name="qend" type="positiveInt" use="required" />
                  <xsd:attribute name="qstart" type="positiveInt" use="required" />
                  <xsd:attribute name="priority" type="nonNegativeInt" use="optional" default="0" />
                </xsd:complexType>
              </xsd:element>

            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>

      <xsd:attribute name="order" type="OrderType" />
      <xsd:attribute name="anchor_name" type="xsd:string" use="required" />
      <xsd:attribute name="anchor_length" type="positiveInt" use="required" />
      <xsd:attribute name="version" type="VersionType" use="required" />
    </xsd:complexType>
  </xsd:element>

  <xsd:simpleType name="StrandType">
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="1" />
      <xsd:enumeration value="-1" />
      <xsd:enumeration value="0" />
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="OrderType">
    <xsd:restriction base="xsd:NMTOKEN">
      <xsd:enumeration value="ascending" />
      <xsd:enumeration value="descending" />
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="VersionType">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="1\.0" />
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="positiveInt" id="positiveInt">
    <xsd:restriction base="xsd:int">
      <xsd:minInclusive value="1"/>
    </xsd:restriction>
  </xsd:simpleType>

  <xsd:simpleType name="nonNegativeInt" id="nonNegativeInt">
    <xsd:restriction base="xsd:int">
      <xsd:minInclusive value="0"/>
    </xsd:restriction>
  </xsd:simpleType>

</xsd:schema>

=== lesfoster/cylindrical-alignment-app/samples/gene_machine/gene_machine_2.cyl.xml
<?xml version="1.0" encoding="UTF-8"?>
<cylinder anchor_name="Sequence_2_From_410_635" anchor_length="3597" version="1.0"
   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="file:///schema/cylinder.xsd">
<entity>
<subentity strand="1" send="3597" sstart="1" qend="3597" qstart="1">
<p value="Anchor" name="subEntityType"/>
<p value="lcl|Sequence_2_From_410_635" name="defline"/>
</subentity>
</entity>
<entity>
  <subentity qend="309" qstart="31" send="309" sstart="31" strand="1"><p value="gene:Genscan" name="subEntityType"/><p value="Genscan" name="gene"/></subentity>
  <subentity qend="2641" qstart="2453" send="2641" sstart="2453" strand="1"><p value="gene:Genscan" name="subEntityType"/><p value="Genscan" name="gene"/></subentity>
</entity>
<entity>
  <subentity qend="322" qstart="31" send="322" sstart="31" strand="1"><p value="gene:HMMGene" name="subEntityType"/><p value="HMMGene" name="gene"/></subentity><subentity qend="2036" qstart="1897" send="2036" sstart="1897" strand="1"><p value="gene:HMMGene" name="subEntityType"/><p value="HMMGene" name="gene"/></subentity><subentity qend="2541" qstart="2326" send="2541" sstart="2326" strand="1"><p value="gene:HMMGene" name="subEntityType"/><p value="HMMGene" name="gene"/></subentity>
  <subentity qend="1588" qstart="1501" send="1588" sstart="1501" strand="1"><p value="exon:HMMGene" name="subEntityType"/><p value="HMMGene" name="gene"/></subentity>
  <subentity qend="2381" qstart="2136" send="2381" sstart="2136" strand="-1"><p value="gene:HMMGene" name="subEntityType"/><p value="HMMGene" name="gene"/></subentity>
</entity>
<entity>
  <subentity qend="357" qstart="263" send="357" sstart="263" strand="1"><p value="gene:Fgenes" name="subEntityType"/><p value="Fgenes" name="gene"/></subentity>
  <subentity qend="1472" qstart="1271" send="1472" sstart="1271" strand="1"><p value="gene:Fgenes" name="subEntityType"/><p value="Fgenes" name="gene"/></subentity>
  <subentity qend="1397" qstart="1271" send="1397" sstart="1271" strand="1"><p value="exon:Fgenes" name="subEntityType"/><p value="Fgenes" name="gene"/></subentity>
</entity>
<entity>
  <subentity qend="579" qstart="299" send="579" sstart="299" strand="1"><p value="repeat_region:RepeatMasker: AluSx" name="subEntityType"/><p value="RepeatMasker: AluSx" name="note"/></subentity>
  <subentity qend="882" qstart="641" send="882" sstart="641" strand="-1"><p value="repeat_region:RepeatMasker: MER7A" name="subEntityType"/><p value="RepeatMasker: MER7A" name="note"/></subentity>
  <subentity qend="1244" qstart="1026" send="1244" sstart="1026" strand="1"><p value="repeat_region:RepeatMasker: AluSq" name="subEntityType"/><p value="RepeatMasker: AluSq" name="note"/></subentity>
  <subentity qend="1933" qstart="1653" send="1933" sstart="1653" strand="1"><p value="repeat_region:RepeatMasker: AluSx" name="subEntityType"/><p value="RepeatMasker: AluSx" name="note"/></subentity>
</entity>

</cylinder>
